<?php

namespace Omnipay\Payrix\Message;

/**
 * Response
 */
class PurchaseResponse extends Response
{
    /**
     * Is the response successful?
     *
     * @return boolean
     */
    public function isSuccessful()
    {
        if (isset($this->data['response']['data'][0]['status'])) {
            return $this->data['response']['data'][0]['status'] == static::APPROVED_STATUS;
        }

        return isset($this->data['response']['data'][0]['id']);
    }

    /**
     * Response Message
     *
     * @return null|string A response message from the payment gateway
     */
    public function getMessage()
    {
        if (isset($this->data['errors'][0]['msg'])) {
            return $this->data['errors'][0]['msg'];
        }

        if (isset($this->data['response']['errors'][0]['msg'])) {
            return $this->data['response']['errors'][0]['msg'];
        }

        if (isset($this->data['message'])) {
            return $this->data['message'];
        }

        return null;
    }

    /**
     * Response code
     *
     * @return null|string A response code from the payment gateway
     */
    public function getCode()
    {
        if (isset($this->data['errors'][0]['code'])) {
            return $this->data['errors'][0]['code'];
        }

        if (isset($this->data['response']['errors'][0]['code'])) {
            return $this->data['response']['errors'][0]['code'];
        }

        if (isset($this->data['status'])) {
            return $this->data['status'];
        }

        return null;
    }

    /**
     * Gateway Reference
     *
     * @return null|string A reference provided by the gateway to represent this transaction
     */
    public function getTransactionReference()
    {
        if (isset($this->data['response']['data'][0]['id'])) {
            return $this->data['response']['data'][0]['id'];
        }
        
        return null;
    }

    /**
     * Get the transaction ID as generated by the merchant website.
     *
     * @return string
     */
    public function getTransactionId()
    {
        if (isset($this->data['response']['data'][0]['order'])) {
            return $this->data['response']['data'][0]['order'];
        }
        
        return '';
    }
}
